---
- name: "update and upgrade packages."
  become: true
  become_method: sudo
  apt:
    upgrade: "yes"
    update_cache: "yes"

- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    apt -y install jq tar gzip git curl
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt-get install -y nodejs

- name: "Install Node.js 13"
  become: true
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  become: true
  npm:
    name: pm2
    global: yes

# - name: "Install PM2 Globally using shell"
#   become: true
#   shell: |
#     npm install pm2 -g

- name: "check for environment variables"
  become_user: ubuntu
  become_method: sudo
  shell: grep -c "^export TYPEORM_CONNECTION" /etc/environment || true
  register: test_grep

# - name: "set environment variables"
#   become: true
#   shell: |
#     echo "# environment variables for udapeople" >> /etc/environment
#     echo "export NODE_ENV=production" >> /etc/environment
#     echo "export ENVIRONMENT=production" >> /etc/environment
#     echo "export TYPEORM_CONNECTION={{ lookup('env', 'TYPEORM_CONNECTION') }}" >> /etc/environment
#     echo "export TYPEORM_ENTITIES=\"./modules/domain/**/*.entity*.{ts,js}"\" >> /etc/environment
#     echo "export TYPEORM_HOST={{ lookup('env', 'TYPEORM_HOST') }}" >> /etc/environment
#     echo "export TYPEORM_PORT={{ lookup('env', 'TYPEORM_PORT') }}" >> /etc/environment
#     echo "export TYPEORM_USERNAME={{ lookup('env', 'TYPEORM_USERNAME') }}" >> /etc/environment
#     echo "export TYPEORM_PASSWORD={{ lookup('env', 'TYPEORM_PASSWORD') }}" >> /etc/environment
#     echo "export TYPEORM_DATABASE={{ lookup('env', 'TYPEORM_DATABASE') }}" >> /etc/environment
#   when: test_grep.stdout == "0"
